  
  ;#-------------------------------------------------ß
  ;|          x64lab  MPL 2.0 License                |
  ;|   Copyright (c) 2009-2012, Marc Rainer Kranz.   |
  ;|            All rights reserved.                 |
  ;ö-------------------------------------------------ä

  ;#-------------------------------------------------ß
  ;| uft-8 encoded üäöß
  ;| update:
  ;| filename:
  ;ö-------------------------------------------------ä

@i_rva top64,\
 top64.locate,\
 top64.parse,\
 top64.free

@i_rva bk64,\
	dlg.open,\
	bk64.listfiles

@i_rva dock64,\
	dock64.init,\
	dock64.info,\
	dock64.id2panel,\
	dock64.bind,\
	dock64.order,\
	dock64.layout,\
	dock64.load,\
	dock64.loadmem,\
	dock64.save,\
	dock64.panel,\
	dock64.discard


